### ISSUE TITLE
Annotator ERROE

### ISSUE THREAD

**Issue by cfz1998** [pauline-ng/SIFT4G_Annotator#6]
Hi！Pauline.
SIFT4G_Annotator prompts me that it cannot find chromosome 1A. But there is only chromosome chr1A in my vcf file. My sift4g database is also chr1A. Why does it prompt me that I cannot find chromosome 1A, do you have any ideas?
![image](https://user-images.githubusercontent.com/60096719/143186897-c04ea5ef-89d3-49c6-9347-07c1a322cd70.png)

Best regards,
Dcf

**Comment by cfz1998** [comment]
And the "New_amino_acid  Position_of_amino_acid_substitution     SIFT_score      SIFT_median_sequence_info       Num_seqs_at_position" is all NA.
![image](https://user-images.githubusercontent.com/60096719/143187646-a1ab8cde-b30b-43c0-bab2-539f12e92de4.png)

**Comment by cfz1998** [comment]
The files in /vol3/agis/chengshifeng_group/zhangchaofan/09.SIFT/scripts_to_build_SIFT_db/wheat/Chr1A/chr1A is：
![image](https://user-images.githubusercontent.com/60096719/143188018-259aab76-a365-4ae8-82c8-4e1c0ee42a92.png)

**Comment by pauline-ng** [comment]
Hi dcf, 

The chromosome column in your vcf file should have **chr1A** in the first column, not **1A.**

Best,
Pauline

**Comment by cfz1998** [comment]
> Hi dcf,
> 
> The chromosome column in your vcf file should have **chr1A** in the first column, not **1A.**
> 
> Best, Pauline

Hi Pauline!
The chromosome column in my vcf file is already chr1A. 
![image](https://user-images.githubusercontent.com/60096719/143189453-c984b20d-089a-483f-922c-e7f0cd610de5.png)

**Comment by pauline-ng** [comment]
Can you try

`grep ^1A <vcf file>`

I think there is at least one variant that starts with "1A".

**Comment by cfz1998** [comment]
> 
OK! Thank you!

**Comment by cfz1998** [comment]
> Can you try
> 
> `grep ^1A <vcf file>`
> 
> I think there is at least one variant that starts with "1A".

Hi Pauline!
The line starting with 1A was not found in the vcf file. This vcf file is annotated with snpEff. Will this affect it?
![image](https://user-images.githubusercontent.com/60096719/143192551-ab0b627a-9782-40d8-a149-03644c7bf0e1.png)

**Comment by cfz1998** [comment]
> Can you try
> 
> `grep ^1A <vcf file>`
> 
> I think there is at least one variant that starts with "1A".

Hi！I know why it is looking for 1A instead of chr1A. The following code removes chr.
![image](https://user-images.githubusercontent.com/60096719/143203604-71265177-085c-4262-a1e0-89bd43030c11.png)

**Comment by cfz1998** [comment]
> 
The file is https://github.com/pauline-ng/SIFT4G_Annotator/blob/4dc97b4489989dff9d28ec1913812387b537b041/SIFT4G_Annotator_code/src/org/siftdna/main/InputFileManager.java

**Comment by cfz1998** [comment]
It works fine. Thank you！Pauline
